In [1]:
import numpy as np

In [60]:
np.set_printoptions(precision=10)

In [19]:
N = 1000
sigma = 1
vector = np.random.normal(loc=0, scale=sigma, size=N)

In [55]:
vector

array([-2.0184500508976062e+00, -1.9639611861479820e+00,
        1.5180317269746285e-01, -6.5307091182339494e-01,
        1.1787764731191976e+00, -2.5551398898433081e-01,
       -1.4112632138537802e+00, -1.1473468496825023e+00,
        7.4628475868260868e-01, -7.6864330736129416e-02,
       -6.0242065199062012e-01, -1.6748755806086025e-02,
        3.7909725317352905e-01,  2.5645897650670063e-01,
       -1.3308322251010860e-01,  1.5285341753287124e-01,
       -9.1677030814782023e-01,  5.8784812974592682e-01,
       -1.1095965935631955e+00,  4.1994602938840925e-01,
       -5.1513280093278813e-01, -1.2422602397163118e+00,
        1.5990816283537246e+00, -1.0967961572667546e+00,
        1.9726478688528562e-01,  8.6629502965153504e-01,
       -8.1198496591300073e-01,  1.1459925375079814e+00,
        2.4452168187439254e+00,  7.2934174267210841e-02,
        1.2276834845400582e+00, -8.3399936279250730e-01,
        9.1027520792829619e-01,  1.5871315193682151e-01,
       -6.3530327442181744e-01,

In [21]:
cols = []
for i in range(4):
    cols.append(np.apply_along_axis(lambda x: np.power(x, i), 0, vector))
X = np.transpose(np.vstack(cols))
X

In [64]:
beta = np.random.normal(loc=0, scale=sigma, size=4)
beta

array([ 0.7919324103,  1.1620911317,  0.6955148049, -0.3052111899])

In [62]:
Y = np.apply_along_axis(lambda r: sum([beta[i] * r[i] for i in range(len(r))]), 1, X)
Y

array([-2.3708275548e+01, -2.1657612564e+01,  1.3867316878e+00,
       -1.4078017272e-01,  1.4077800391e+01,  6.1810684318e-01,
       -7.0905826044e+00, -3.3869708897e+00,  5.8259384836e+00,
        8.6217921815e-01,  9.3911597143e-03,  9.6732525735e-01,
        2.4072661220e+00,  1.7777020383e+00,  7.7753876279e-01,
        1.3900845081e+00, -1.3942009109e+00,  4.0249524824e+00,
       -2.9901411083e+00,  2.6651938313e+00,  2.1903353140e-01,
       -4.5231651683e+00,  2.8225153232e+01, -2.8623224475e+00,
        1.5419747334e+00,  7.5844948942e+00, -7.8744153980e-01,
        1.3252004701e+01,  8.2308329163e+01,  1.1633783922e+00,
        1.5378478465e+01, -9.0170341161e-01,  8.3233729017e+00,
        1.4089877489e+00, -8.5435452279e-02, -1.6247981091e+01,
       -4.1000033087e-01,  6.7736030333e-01,  6.5940053140e-01,
       -3.9318329767e+00,  7.7948500640e+00, -1.8512586355e+00,
        1.0491431625e+01,  6.4762166681e-01,  1.3807642974e+01,
        1.2915735207e+00,  3.3124014489e

In [63]:
beta_hat = np.matmul(np.matmul(np.linalg.inv(np.matmul(np.transpose(X), X)), np.transpose(X)), Y)
beta_hat

array([1., 2., 3., 4.])